name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    name: Geração da Cobrinha
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: orafaeldantas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Listar arquivos no repositório
        run: |
          echo "Arquivos no repositório após geração:"
          ls -la || echo "Erro ao listar arquivos"
      
      - name: Listar arquivos gerados na pasta dist/
        run: |
          echo "Arquivos em dist/"
          ls -la dist || echo "Pasta dist não encontrada"

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist/

  commit-snake:
    needs: generate-snake
    runs-on: ubuntu-latest
    name: Commit da Cobrinha no repositório
    steps:
      - name: Baixar artefatos
        uses: actions/download-artifact@v4
        with:
          name: snake-artifacts
          path: dist/

      - name: Verificar conteúdo baixado
        run: |
          echo "Conteúdo de dist após download:"
          ls -la dist || echo "Nada foi baixado"

      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          ref: output
          clean: false

      - name: Configurar Git
        run: |
          git config --global user.name "orafaeldantas"
          git config --global user.email "rafael.hfdantas@outlook.com"  # Seu e-mail do GitHub

      - name: Verificar se a branch output existe
        run: |
          git branch -r

      - name: Commit e push da cobrinha
        run: |
          if [ -d "dist" ]; then
            git add dist/
            git commit -m "Atualiza animação da cobrinha [automático]" || echo "Nada novo para commitar"
            git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/orafaeldantas/orafaeldantas.git HEAD:output
          else
            echo "⚠️ A pasta dist/ não existe. Nada para commitar."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
