name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite UTC
  workflow_dispatch:     # Permite execução manual
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    name: Gera e envia a cobrinha
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: orafaeldantas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit da cobrinha na branch output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone --branch=output https://github.com/orafaeldantas/orafaeldantas.git output
          cp -r dist/* output/
          cd output

          git add .
          git commit -m "Atualiza animação da cobrinha [auto]" || echo "Nada novo para commitar"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/orafaeldantas/orafaeldantas.git output
