name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # executa todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: orafaeldantas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Configurar git
        run: |
          git config --global user.name "orafaeldantas"
          git config --global user.email "rafael.hfdantas@outlook.com"
      
      - name: Commit e push do SVG
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizar animação da cobrinha"
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/orafaeldantas/orafaeldantas.git HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
