name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à meia-noite
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    name: Geração da Cobrinha
    steps:
      - name: Gera a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: orafaeldantas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Verificar arquivos gerados
        run: ls -la dist/

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist/

  commit-snake:
    needs: generate-snake
    runs-on: ubuntu-latest
    name: Commit da Cobrinha no Repositório
    steps:
      - name: Baixar artefatos
        uses: actions/download-artifact@v4
        with:
          name: snake-artifacts
          path: dist/

      - name: Verificar conteúdo baixado
        run: ls -la dist/

      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          ref: output  # Certifique-se de que a branch 'output' existe
          clean: false

      - name: Configurar Git
        run: |
          git config --global user.name "orafaeldantas"
          git config --global user.email "rafael.hfdantas@outlook.com"

      - name: Commit e push da cobrinha
        run: |
          git add dist/
          git commit -m "Atualiza animação da cobrinha [automático]" || echo "Nada para commitar"
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/orafaeldantas/orafaeldantas.git HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
