name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: orafaeldantas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inicializar repositório
        run: git init

      - name: Configurar git
        run: |
          git config --global user.name "orafaeldantas"
          git config --global user.email "rafael.hfdantas@outlook.com"

      - name: Criar diretório dist (se necessário)
        run: mkdir -p dist

      - name: Commit e push do SVG
        run: |
          git add dist/
          git commit -m "Atualizar animação da cobrinha"
          git branch -M output
          git remote add origin https://github.com/orafaeldantas/orafaeldantas.git || true
          git push -f https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/orafaeldantas/orafaeldantas.git output
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
